// Halftone plates generated by scripts/plates.ts (runs before dev and build).
const files = import.meta.glob<{ default: ImageMetadata }>('/src/generated/plates/*.png', { eager: true });

/** URL of a tool's halftone plate, or null when it hasn't been generated (the colour image shows instead). */
export const inkFor = (slug: string, kind: 'thumb' | 'icon') =>
  files[`/src/generated/plates/${slug}${kind === 'icon' ? '-icon' : ''}.png`]?.default.src ?? null;
